version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5.1-browsers
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PHANTOMJS_VERSION: 2.1.1
          CI: true
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: /home/circleci/community
    steps:
      - run:
          name: Install NPM
          command: |
            curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          - dependency-cache
      - restore_cache:
          keys:
          - npm-cache-{{ .Branch }}
          - npm-cache
      - run: bin/setup
      - run: bin/test_suite
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: dependency-cache
          paths: "deps"
      - save_cache:
          key: npm-cache-{{ .Branch }}
          paths: "node_modules"
      - save_cache:
          key: npm-cache
          paths: "node_modules"
