version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.4-node-browsers
        environment:
          PHANTOMJS_VERSION: 2.1.1
      - image: circleci/postgres:10.3-alpine-ram
        environment:
          POSTGRES_USER: postgres
    working_directory: /home/circleci/community
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          - dependency-cache-{{ arch }}-{{ .Branch }}
          - dependency-cache-{{ arch }}
      - restore_cache:
          keys:
          - npm-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - npm-cache-{{ arch }}-{{ .Branch }}
          - npm-cache-{{ arch }}
      - run: mix local.hex --force && mix local.rebar --force && mix deps.get && npm i
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: dependency-cache-{{ arch }}
          paths: "deps"
      - save_cache:
          key: npm-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths: "node_modules"
      - save_cache:
          key: npm-cache-{{ arch }}-{{ .Branch }}
          paths: "node_modules"
      - save_cache:
          key: npm-cache-{{ arch }}
          paths: "node_modules"
      - run: bin/test_suite
experimental:
  notify:
    branches:
      only:
        - master
